

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ebookio.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ebookioEntities : DbContext
{
    public ebookioEntities()
        : base("name=ebookioEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_admin> tbl_admin { get; set; }

    public virtual DbSet<tbl_publisher> tbl_publisher { get; set; }

    public virtual DbSet<tbl_language> tbl_language { get; set; }

}

}

