
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ebookio.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_admin
{

        public int admin_id { get; set; }
        public string admin_username { get; set; }
        [Required(ErrorMessage = "Email Id Is Required")]
        [RegularExpression("^([0-9a-zA-Z]([-\\.\\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,9})$", ErrorMessage = "Invalid Email Id")]
        [DisplayName("Email Id")]
        public string admin_emailid { get; set; }
        public Nullable<long> admin_mobile { get; set; }
        [Required(ErrorMessage = "Password Is Required")]
        // [RegularExpression(@"(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$",ErrorMessage = "Please Enter At least One UpperCase, LowerCase, Numbers, Symbols, 8 Characters")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string admin_password { get; set; }
        public bool RememberMe { get; set; }

    }

}
