//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebookio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_publisher
    {
        public int publisher_id { get; set; }
        public string publisher_name { get; set; }
    }
}
